 mail:
    host: smtp.gmail.com
    port: 587
    username: aswinime28@gmail.com
    password: Helloaswini28@
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com